name = "Todo Checker"
shortcode = "@sdfsdf/chcker"
description = "Checks for TODO comments and flags them."
tags = ["todo", "comment-checker"]
repository = "https://github.com/siddhant-deepsource/2do-checker"
documentation = ""
bug_tracker = ""

[environment_variables]

[analysis]
  command = "/app/todo-checker"

[build]
  engine = "docker"
  dockerfile = ""
  script = ""

[test]
  command = ""
