name = "Todo-Checker"
shortcode = "@test-namespace/todo-checker"
description = "Checks for TODO comments in code."
tags = ["todo-comments", "checker", "static-analysis"]
repository = "https://github.com/siddhant-deepsource/2do-checker"
documentation = ""
bug_tracker = ""

[environment_variables]

[analysis]
  command = "/app/todo-checker"

[build]
  engine = "docker"
  dockerfile = ""
  script = ""

[test]
  command = ""
