name = "Test Analyzer"
shortcode = "@test-ns/analyzer-2"
description = "Checks for TODO comments and flags them."
tags = ["ochecker"]
repository = "https://github.com/siddhant-deepsource/2do-checker"
documentation = ""
bug_tracker = ""

[environment_variables]

[analysis]
  command = "/app/todo-checker"

[build]
  engine = "docker"
  dockerfile = ""
  script = ""

[test]
  command = ""
